/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectIdRouteImport } from './routes/subject.$id'
import { Route as SubjectIdIndexRouteImport } from './routes/subject.$id.index'
import { Route as SubjectIdModuleModuleIdRouteImport } from './routes/subject.$id.module.$moduleId'
import { Route as SubjectIdModuleModuleIdIndexRouteImport } from './routes/subject.$id.module.$moduleId.index'
import { Route as SubjectIdModuleModuleIdMarksMarksIdRouteImport } from './routes/subject.$id.module.$moduleId.marks.$marksId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectIdRoute = SubjectIdRouteImport.update({
  id: '/subject/$id',
  path: '/subject/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectIdIndexRoute = SubjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubjectIdRoute,
} as any)
const SubjectIdModuleModuleIdRoute = SubjectIdModuleModuleIdRouteImport.update({
  id: '/module/$moduleId',
  path: '/module/$moduleId',
  getParentRoute: () => SubjectIdRoute,
} as any)
const SubjectIdModuleModuleIdIndexRoute =
  SubjectIdModuleModuleIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SubjectIdModuleModuleIdRoute,
  } as any)
const SubjectIdModuleModuleIdMarksMarksIdRoute =
  SubjectIdModuleModuleIdMarksMarksIdRouteImport.update({
    id: '/marks/$marksId',
    path: '/marks/$marksId',
    getParentRoute: () => SubjectIdModuleModuleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/subject/$id': typeof SubjectIdRouteWithChildren
  '/subject/$id/': typeof SubjectIdIndexRoute
  '/subject/$id/module/$moduleId': typeof SubjectIdModuleModuleIdRouteWithChildren
  '/subject/$id/module/$moduleId/': typeof SubjectIdModuleModuleIdIndexRoute
  '/subject/$id/module/$moduleId/marks/$marksId': typeof SubjectIdModuleModuleIdMarksMarksIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/subject/$id': typeof SubjectIdIndexRoute
  '/subject/$id/module/$moduleId': typeof SubjectIdModuleModuleIdIndexRoute
  '/subject/$id/module/$moduleId/marks/$marksId': typeof SubjectIdModuleModuleIdMarksMarksIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/subject/$id': typeof SubjectIdRouteWithChildren
  '/subject/$id/': typeof SubjectIdIndexRoute
  '/subject/$id/module/$moduleId': typeof SubjectIdModuleModuleIdRouteWithChildren
  '/subject/$id/module/$moduleId/': typeof SubjectIdModuleModuleIdIndexRoute
  '/subject/$id/module/$moduleId/marks/$marksId': typeof SubjectIdModuleModuleIdMarksMarksIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/subject/$id'
    | '/subject/$id/'
    | '/subject/$id/module/$moduleId'
    | '/subject/$id/module/$moduleId/'
    | '/subject/$id/module/$moduleId/marks/$marksId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/subject/$id'
    | '/subject/$id/module/$moduleId'
    | '/subject/$id/module/$moduleId/marks/$marksId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/subject/$id'
    | '/subject/$id/'
    | '/subject/$id/module/$moduleId'
    | '/subject/$id/module/$moduleId/'
    | '/subject/$id/module/$moduleId/marks/$marksId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SubjectIdRoute: typeof SubjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$id': {
      id: '/subject/$id'
      path: '/subject/$id'
      fullPath: '/subject/$id'
      preLoaderRoute: typeof SubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$id/': {
      id: '/subject/$id/'
      path: '/'
      fullPath: '/subject/$id/'
      preLoaderRoute: typeof SubjectIdIndexRouteImport
      parentRoute: typeof SubjectIdRoute
    }
    '/subject/$id/module/$moduleId': {
      id: '/subject/$id/module/$moduleId'
      path: '/module/$moduleId'
      fullPath: '/subject/$id/module/$moduleId'
      preLoaderRoute: typeof SubjectIdModuleModuleIdRouteImport
      parentRoute: typeof SubjectIdRoute
    }
    '/subject/$id/module/$moduleId/': {
      id: '/subject/$id/module/$moduleId/'
      path: '/'
      fullPath: '/subject/$id/module/$moduleId/'
      preLoaderRoute: typeof SubjectIdModuleModuleIdIndexRouteImport
      parentRoute: typeof SubjectIdModuleModuleIdRoute
    }
    '/subject/$id/module/$moduleId/marks/$marksId': {
      id: '/subject/$id/module/$moduleId/marks/$marksId'
      path: '/marks/$marksId'
      fullPath: '/subject/$id/module/$moduleId/marks/$marksId'
      preLoaderRoute: typeof SubjectIdModuleModuleIdMarksMarksIdRouteImport
      parentRoute: typeof SubjectIdModuleModuleIdRoute
    }
  }
}

interface SubjectIdModuleModuleIdRouteChildren {
  SubjectIdModuleModuleIdIndexRoute: typeof SubjectIdModuleModuleIdIndexRoute
  SubjectIdModuleModuleIdMarksMarksIdRoute: typeof SubjectIdModuleModuleIdMarksMarksIdRoute
}

const SubjectIdModuleModuleIdRouteChildren: SubjectIdModuleModuleIdRouteChildren =
  {
    SubjectIdModuleModuleIdIndexRoute: SubjectIdModuleModuleIdIndexRoute,
    SubjectIdModuleModuleIdMarksMarksIdRoute:
      SubjectIdModuleModuleIdMarksMarksIdRoute,
  }

const SubjectIdModuleModuleIdRouteWithChildren =
  SubjectIdModuleModuleIdRoute._addFileChildren(
    SubjectIdModuleModuleIdRouteChildren,
  )

interface SubjectIdRouteChildren {
  SubjectIdIndexRoute: typeof SubjectIdIndexRoute
  SubjectIdModuleModuleIdRoute: typeof SubjectIdModuleModuleIdRouteWithChildren
}

const SubjectIdRouteChildren: SubjectIdRouteChildren = {
  SubjectIdIndexRoute: SubjectIdIndexRoute,
  SubjectIdModuleModuleIdRoute: SubjectIdModuleModuleIdRouteWithChildren,
}

const SubjectIdRouteWithChildren = SubjectIdRoute._addFileChildren(
  SubjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SubjectIdRoute: SubjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
